### ISSUE TITLE
Ajax request to server, which uses modmellon

### ISSUE THREAD

**Issue by 7fantasy7** [UNINETT/mod_auth_mellon#103]
Hello guys, as I see in documentation:
        #           There is a special handling of AJAX requests, that are
        #           identified by the "X-Request-With: XMLHttpRequest" HTTP
        #           header. Since no user interaction can happen there,
        #           we always fail unauthenticated (not logged in) requests
        #           with a 403 Forbidden error without redirecting to the IdP.

So, the question is: isn't there way to use modmellon auth to ajax requests?
If i need for example to insert iframe from my site to another one with some widget, and to check authentification for ajax requests, this iframe app makes.

Thanks in advance!

**Comment by olavmrk** [comment]
No, SAML-authentication cannot be used for AJAX requests. Typically SAML authentication requires interacting with a web page to enter the username & password, and then transmiting authentication data back to the SP using a self-posting form on a different web page. Getting that to work in an AJAX request is next to impossible.

Do however note that this only applies to the case where you aren't authenticated. If you are authenticated (e.g. running an AJAX request from a web page on your site back to your site), this code path doesn't trigger, since you are already authenticated.
