### ISSUE TITLE
Wrong Status Code for Preflight?

### ISSUE THREAD

**Issue by dtissen** [UNINETT/mod_auth_mellon#117]
Hi, 
It seems for me that mod_auth_mellon sends a wrong status code for CORS Preflight Request.

The Environment and Status:
I've managed using Javascript to get an valid mellon-cookie. Since I have a valid mellon-cookie i am allowed to send requests to the protected ressource (theoretically). The protected resource itself is also using Cookies (Login at the Application) therefor i will make an application specific "JSON login" using javascript with CORS-Support and Content-Type "application/json".

The CORS Specification by the w3 (https://fetch.spec.whatwg.org/#http-cors-protocol) says that a "preflight" with the Method "Options" is necassary. Most Browsers who suppert CORS will now make a preflight call. The Description of this Preflight call is: "A CORS-preflight request is a CORS request that checks to see if the CORS protocol is understood. It uses `OPTIONS` as method and includes these headers"

It seems that mod_auth_mellon actually does not "support CORS"? Actually the preflight-call response from mellon is (303 See Other) since a preflight call NEVER sends Cookies and therefore did not send the mellon-cookie.

I think mellon should send a status code 200 or 204. I am right? Does mellon support CORS?

**Comment by dtissen** [comment]
I managed to solve it that way that i have created RewriteCondition in the Apache Service to send an 200 when getting an 303 See Other. Is this the correct way to do? Looks a little bit strange....

**Comment by olavmrk** [comment]
Hi,

as far as I understand CORS, this is not something that mod_auth_mellon can handle. The reason for the preflight requests is to check whether allowing CORS requests is safe. CORS requests are only safe if the application supports CORS. Since it is up to the application whether to support this or not, this is not something that mod_auth_mellon can handle.

Instead, the proper solution is probably to change `MellonEnable auth` to `MellonEnable info` for the API endpoints, and then add code in the API handlers to (1) send the proper headers in reply to preflight OPTIONS requests and (2) on non-options request, check if this is an authenticated user (in which case mod_auth_mellon will pass information about the current user to the application).
