### ISSUE TITLE
ECP fails with LASSO_SERVER_ERROR_PROVIDER_NOT_FOUND

### ISSUE THREAD

**Issue by mdutton3** [Uninett/mod_auth_mellon#129]
lasso_login_build_authn_request_msg returns LASSO_SERVER_ERROR_PROVIDER_NOT_FOUND
https://github.com/UNINETT/mod_auth_mellon/blob/2c2e19d96069f2d94d6c68f50e3ef2175a412cfb/auth_mellon_handler.c#L2852

Digging in, it looks like Lasso is complaining that neither the remote URL or the remote provider ID is set. From my limited understanding of ECP, this would seem normal.  Additionally, `lasso_login_init_authn_request` ignores the `remote_providerID` if the `http_method` is `LASSO_HTTP_METHOD_PAOS`.

Building off mod_auth_mellon @ 6ff514ceecbad571d0d599cc2d4b2ae90b372a47 and Lasso @ https://github.com/mdutton3/lasso/commit/c62ad0047eafb6eaaf1370fea6f35214cc85e02e

**Comment by mdutton3** [comment]
This may be a Lasso issue but I'm still getting familiar with mod_auth_mellon and can't tell yet.

**Comment by luyandasiko** [comment]
If I can quickly jump in as it seems like somewhere along the conversation you guys are having I am experiencing the same issue. I practically no nothing about this setup I am junior and I am so frustrated because next week is deadline to a website that was built that is using this module. The top most issue before this one would provide proper context. Basically I am getting a "Lasso" Provider ID issue as well on my end and I cannot put my finger on it.

It seems the SP does hit the IdP with the current descriptor setup yet the response I get is that I am trying to logout when I haven't logged in in the first place... Any ideas you may want care to share?

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
