### ISSUE TITLE
MellonIdP* is ignored

### ISSUE THREAD

**Issue by grawity** [UNINETT/mod_auth_mellon#17]
So I'm trying to use this module on Debian jessie (auth_mellon 0.9.1-1, Apache 2.4.10-9, Lasso 2.4.1-1) and it just won't pick up any metadata configuration:

> Error adding IdP to lasso server object. Please verify the following configuration directives: MellonIdPMetadataFile and MellonIdPPublicKeyFile.

I _do_ have both configured, pointing to valid xml and certificate files. I tried configuring them in `<VirtualHost>`, in `<Directory>`, in `<Location>`.

I went as far as adding debug 'printf's to the MellonIdPMetadataFile handler where they show the correct values being inserted, and to am_server_add_providers() where `cfg->idp_metadata` is completely _empty_.

I don't know why though (this is already beyond my Apache knowledge).

**Comment by olavmrk** [comment]
Hi,

if the value is empty when it initializes the Lasso server library, you most likely have an error in your Apache config somewhere. Make sure that the configuration section you have added actually applies to the URL of the request you get the error for.

Since this is an issue tracker and not a support forum, I am closing this issue. Any support questions should be directed to the mailing list instead.
