### ISSUE TITLE
apr_global_mutex_lock() failed 

### ISSUE THREAD

**Issue by LtCMDstone** [Uninett/mod_auth_mellon#191]
Hey i got an error for auth_mellon:

`[auth_mellon:error] [pid 124214] [client IP:56644] apr_global_mutex_lock() apr_global_mutex_lock() failed [22]: Invalid argument, referer: adress of IdP.`

If this error is happening the whole apache is crashing until I restart it.
I cant reproduce it and it's not happening all the time, only now and then, so I don't have any starting point.

Can anyone of you help me with this problem?

**Comment by olavmrk** [comment]
Hi,

no direct suggestions from me, but could you check if there is an error that happens before `apr_global_mutex_lock()` starts failing? I'm wondering if an Apache worker process may have crashed while holding the lock, leaving it in an invalid state.

**Comment by LtCMDstone** [comment]
Hey thanks for the reply!
Sometimes, not always, i get this error several seconds befor the mutex error
`[auth_mellon:error] [pid 115672] am_new_request_session() failed`

**Comment by olavmrk** [comment]
Hi,

I had a look at that code path now, and an `am_new_request_session() failed`-message should always be preceded by one of the following messages:

* Error creating session id.
* apr_global_mutex_lock() failed
* Unable to store cookie token in new session

Are you certain that the `am_new_request_session() failed`-message is the only one logged?
Not that the messages can show up in different Apache error log files, depending on how your web server is configured.

**Comment by LtCMDstone** [comment]
Hey,

like i said the `am_new_request_session()` and `apr_global_mutex_lock()` errors are the only ones.
Here the whole error log from today, we dont have another relevant one.

`[Fri Nov 30 09:30:16.438814 2018] [auth_mellon:error] [pid 115672] [client IP:56024] apr_global_mutex_lock() failed [22]: Invalid argument, referer: IdP
[Fri Nov 30 09:30:16.438936 2018] [auth_mellon:error] [pid 115672] am_new_request_session() failed
[Fri Nov 30 09:33:36.739487 2018] [auth_mellon:error] [pid 124419] [client IP:56298] apr_global_mutex_lock() failed [22]: Invalid argument
[Fri Nov 30 09:33:36.739588 2018] [auth_mellon:error] [pid 124419] am_new_request_session() failed
[Fri Nov 30 09:33:41.209718 2018] [auth_mellon:error] [pid 115466] [client IP:56299] apr_global_mutex_lock() failed [22]: Invalid argument
[Fri Nov 30 09:33:42.110082 2018] [auth_mellon:error] [pid 115882] [client IP:56301] apr_global_mutex_lock() failed [22]: Invalid argument, referer: IdP
[Fri Nov 30 09:33:42.110162 2018] [auth_mellon:error] [pid 115882] am_new_request_session() failed
[Fri Nov 30 09:36:55.176250 2018] [auth_mellon:error] [pid 124214] [client IP:56644] apr_global_mutex_lock() failed [22]: Invalid argument
[Fri Nov 30 09:36:56.146177 2018] [auth_mellon:error] [pid 129758] [client IP:56645] apr_global_mutex_lock() failed [22]: Invalid argument, referer: IdP
[Fri Nov 30 09:36:56.146277 2018] [auth_mellon:error] [pid 129758] am_new_request_session() failed
[Fri Nov 30 09:39:44.253736 2018] [auth_mellon:error] [pid 129546] [client IP:56801] apr_global_mutex_lock() failed [22]: Invalid argument
[Fri Nov 30 09:39:45.214875 2018] [auth_mellon:error] [pid 124829] [client IP:56803] apr_global_mutex_lock() failed [22]: Invalid argument, referer: IdP
[Fri Nov 30 09:39:45.214990 2018] [auth_mellon:error] [pid 124829] am_new_request_session() failed
[Fri Nov 30 09:46:10.181236 2018] [auth_mellon:error] [pid 124419] [client IP:57155] apr_global_mutex_lock() failed [22]: Invalid argument, referer: IdP
[Fri Nov 30 09:46:10.181331 2018] [auth_mellon:error] [pid 124419] am_new_request_session() failed
[Fri Nov 30 09:46:10.296811 2018] [auth_mellon:error] [pid 115882] [client IP:57156] apr_global_mutex_lock() failed [22]: Invalid argument, referer: IdP
`

thanks for your help!

**Comment by olavmrk** [comment]
I have looked through the relevant code, including the implementation of `apr_global_mutex_lock()`, and the only way it should fail with the "Invalid argument" error is if an underlying system call fails, typically because the lock object specified is invalid. However, there are no clear reasons for why it should be invalid.

To make matters more complicated, the actual implementation of the mutex depends on the current platform, so there is no easy way to tell exactly what mutex implementation is in use. The possible calls that may return "Invalid argument" (EINVAL) I find are:

* [`sem_wait(...)`](https://github.com/apache/apr/blob/1.6.5/locks/unix/proc_mutex.c#L160): http://man7.org/linux/man-pages/man3/sem_wait.3.html#ERRORS
* [`semop(...)`](https://github.com/apache/apr/blob/1.6.5/locks/unix/proc_mutex.c#L279): http://man7.org/linux/man-pages/man2/semop.2.html#ERRORS
* [`pthread_mutex_lock(...)`](https://github.com/apache/apr/blob/1.6.5/locks/unix/proc_mutex.c#L539): http://man7.org/linux/man-pages/man3/pthread_mutex_lock.3p.html#ERRORS
* [`fcntl(...)`](https://github.com/apache/apr/blob/1.6.5/locks/unix/proc_mutex.c#L695): http://man7.org/linux/man-pages/man2/fcntl.2.html#ERRORS
* [`flock(...)`](https://github.com/apache/apr/blob/1.6.5/locks/unix/proc_mutex.c#L842): http://man7.org/linux/man-pages/man2/flock.2.html#ERRORS

For the error descriptions I find, the typical error would be that the mutex/semaphore does not exist, but I cannot tell why that would be. Unfortunately, without something more to go on, this is really hard to debug.

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
