### ISSUE TITLE
Improper handling of "+" between ReturnTo and RelayState

### ISSUE THREAD

**Issue by spencerryan** [Uninett/mod_auth_mellon#214]
Hello,

I've tested this with 0.13.1-1ubuntu0.1 and 0.14.2-1ubuntu1. It appears that somewhere between parsing the "ReturnTo" argument and when it gets encoded into RelayState something goes wrong with any"+" characters. 

Our specific use case is for Atlassian's Confluence, it uses +'s in URLs. If I force a login with:

`https://example.com/secret/endpoint/login?ReturnTo=/display/ST/IT+Infrastructure+Team`

The RelayState parameter in the URL generated has all the +'s turned into %2520 (%20, which turns into a space). Once login succeeds the destination URL has all the +'s turned into " ", which fails in Confluence as it's not the correct request URI. (Here's the output from when diagnostics are enabled)

`SAML AuthnRequest: http_method=LASSO_HTTP_METHOD_REDIRECT URL=https://example.com/(SNIP)RelayState=%2Fdisplay%2FST%2FIT%20Infrastructure%20Team`

If I again force a login with login? and pre-encode them to %2B (so `ReturnTo=/display/ST/IT%2BInfrastructure%2BTeam`) they get passed back correctly and the proper URL is loaded post login. 

When enabling diagnostics the + characters show up properly: 
`query args: ReturnTo=/display/ST/IT+Infrastructure+Team`

**Comment by olavmrk** [comment]
Hi,

just to clarify: You are manually creating the login-URL, manually setting the `ReturnTo`-parameter? It is not autogenerated by mod_auth_mellon?

Whenever you pass add a query parameter to an URL you need to URL encode that query parameter. E.g. consider a path with an existing query string: `https://example.com/show?type=document&id=123`

If you fail to URL encode that string when setting it as `ReturnTo`, you will access the following URL:

```
https://example.com/secret/endpoint/login?ReturnTo=/show?type=document&id=123
```

Parsing that URL gives you two query parameters:

* `ReturnTo`: `/show?type=document`
* `id`: `123`

mod_auth_mellon will then ignore the `id`-parameter, which means that the user will not be directed to the correct URL after login.

Instead, always URL encode your query parameters:

```
https://example.com/secret/endpoint/login?ReturnTo=/show%3Ftype%3Ddocument%26id%3D123
```

This ensures that it is parsed correctly.

The behavior you are seeing with `+` being changed to `%20` in the `RelayState` parameter is correct. `+` in a query parameter is the same as a space. See for example: https://www.google.com/?q=test+with+plus+for+space

The reason the `+` is converted to `%20` in RelayState is that they are equivalent, and it is simpler to just use a consistent set of conversion rules. The full process is:

1. You access `https://example.com/secret/endpoint/login?ReturnTo=/display/ST/IT+Infrastructure+Team`
2. mod_auth_mellon URL decodes its query parameters; `ReturnTo` is decoded to `/display/ST/IT Infrastructure Team`
3. mod_auth_mellon builds an authentication request; since we pass the URL in a query parameter we need to URL encode it; it is encoded as `RelayState=/display/ST/IT%20Infrastructure%20Team`
4. [login takes place, the IdP will have URL decoded the relay state parameter and added it in the login data that is sent back to the SP. The URL encoding here is actually done by the browser in most cases]
5. mod_auth_mellon receives a authentication response. Here `RelayState` may be either `/display/ST/IT%20Infrastructure%20Team` or `/display/ST/IT+Infrastructure+Team`, depending on the behavior of the browser
6. mod_auth_mellon URL decodes the `RelayState` parameter, and gets `/display/ST/IT Infrastructure Team` (same as in step 2)
7. mod_auth_mellon sets a `Location`-header with the requested URL: `Location: /display/ST/IT Infrastructure Team`. which is an invalid URL.

**Comment by spencerryan** [comment]
Thanks for that feedback. This led me down the rabbit hole to figure out why this wasn't working. I'm going to close this.

What ended up occurring was I had followed a guide that put mellon in "info" mode with a few "Allow from" directives to act as an IP whitelist to skip auth. It was unclear to me at the time but the way the guide had this working was to set a custom 401 handler that was setting ReturnTo:

`ErrorDocument 401 "<html><head><meta http-equiv=\"refresh\" content=\"0; URL='/secret/endpoint/login?ReturnTo=%{escape:%{REQUEST_URI}}'\" /></head></html>"`

Oddly enough Apache's escape wasn't turning the + into %2B.


My intended goal was to have RFC1918 space not require auth, but everything else should hit our IdP.  Thanks again for the feedback/Explanation. This is what ended up working for me:

```  <Location />
    <If "-R '10.0.0.0/8' || -R '172.16.0.0/12' || -R '192.168.0.0/16'">
       Require all granted
    </If>
    <Else>
       Require valid-user
       MellonEnable "auth"
       AuthType "Mellon"
      (SNIP)
    </Else>
  </Location>`
