### ISSUE TITLE
Put number of multi-valued values to separate variable

### ISSUE THREAD

**Issue by adelton** [UNINETT/mod_auth_mellon#26]
When consuming multi-valued attributes in Spacewalk and Foreman (please also see https://github.com/UNINETT/mod_auth_mellon/issues/24), the code expects variable suffixed _N to exist and hold the number of values. So for example, if the user is a member of two groups, and REMOTE_USER_GROUP_1=test1 and REMOTE_USER_GROUP_2=test2 are set, REMOTE_USER_GROUP_N would be set to 2 as well. The behaviour is also mentioned at http://www.freeipa.org/page/Environment_Variables#Proposed_Additional_Variables.
That makes it easier for the code to know how many values to expect and also plays the role of a safeguard.
I'd like to propose a patch to mod_auth_mellon to be able to populate the _N variable as well. Before I present a code though, would you prefer for it to be set unconditionally, or would you prefer a configuration option for it?

**Comment by olavmrk** [comment]
On one hand, I would like to limit the amount of options that are present, since it becomes rather unwieldy after a while, but in this case it is too easy to imagine code that would break with this change. E.g. something like this in Python:

```python
eduPersonAffiliation = [ v for k,v in os.environ.items() if k.startswith('MELLON_eduPersonAffiliation_') ]
```

(Basically, grab every value starting with the expected prefix.)

I therefore think it would be best to add this through a new option.

**Comment by olavmrk** [comment]
Patch merged -- closing issue.
