### ISSUE TITLE
Session is cleared after apache server reload

### ISSUE THREAD

**Issue by shredder12** [UNINETT/mod_auth_mellon#36]
It seems the session is cleared once apache2 is reloaded. Is there is way to persist the session beyond restarts? I tested replay post method, but unfortunately it has not affect. I don't see any data in replay post directory either.

Thoughts?

**Comment by olavmrk** [comment]
That is correct -- as long as the sessions are kept in-memory, they are lost when the server is restarted. (That includes a simple server reload, since Apache actually starts a new set of server processes at that time.)

I have considered adding support for some sort of external session store, but so far this hasn't been enough of a problem for me that I have prioritized it. Normally, the user is simply silently logged back in on the next request.

**Comment by shredder12** [comment]
Thank you for the clarification. I tried to use the 'replay post request' feature to ensure transparent log in after a server reload, but it keeps redirecting me back to Identity provider's portal. I believe its not working since I don't see anything in the replay post directory. Kindly let me know if I am missing something or if you need more information.

**Comment by thijskh** [comment]
It was always my understanding that mod_mellon intended to be the simple, in-memory solution, and that if you need more complex session management options, you could consider to use an advanced product like Shibboleth.

**Comment by olavmrk** [comment]
> It was always my understanding that mod_mellon intended to be the simple, in-memory solution.

Simple, yes, but not necessarily completely in-memory. If I added an option for an external session store, it would be (1) simple, probably something like an external memcache-server or something similar, and (2) optional, with the in-memory session store being the default.

@shredder12: Regarding the post replay issue, that is more of a support question, which probably belongs on the mailing list and not here.

I'm closing this issue for now.
