### ISSUE TITLE
Ability to skip /login HTTP 303 redirect

### ISSUE THREAD

**Issue by yarki** [UNINETT/mod_auth_mellon#39]
Folks,

It looks like in case of SP-initiated flow and JavaScript-enabled browser we could render SAMLRequest HTML form and POST it right away (thus bypassing HTTP 303 redirect to /login?ReturnTo=mysite)

Are there any strong reasons for doing the redirect in this case?

Thanks.

**Comment by olavmrk** [comment]
Because it leaves us with one path through the login process, keeping the code simpler. We used to redirect directly to the IdP with the login request when the situation allowed it, but that complicates the code, with no significant gain.

Is there a specific reason for why you find the redirect problematic?

**Comment by yarki** [comment]
We are striving for sub-second page load times (even for not yet authenticated users)
One more redirect seems to cause ~165 ms overhead :)
(EU-hosted server, US-based user)

**Comment by olavmrk** [comment]
I do see you point, but in this case I think I will have to prioritize code maintainability. I was very happy when I managed to get rid of that dual logic for normal login flows, so I don't want to add it back.
