### ISSUE TITLE
lasso error:  The profile cannot verify a signature on the message

### ISSUE THREAD

**Issue by xueshanf** [UNINETT/mod_auth_mellon#59]
I am getting errors when testing auth_mellon 0.10  against a simpleSAMLphp idP  server:

```
Error processing authn response. Lasso error: [440] The profile cannot verify a signature on the message, referer: https://example.com/simplesamlphp/module.php/saml/sp/saml2-acs.php/default-sp
```
 
It occurs that  the idP uses sha256 signature method, like so in SAML response:

```
....
Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
...
```

I do have a working SP that works against an idP server that uses default sha1. 

Question - does lasso support sha256? SP server has this configuration:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

liblasso3: 2.4.0-2build1
auth-mellon: 0.10
Apache:2.4
OpenSSL 1.0.1f

Let me know if you need more information.  Thanks!
Xueshan

**Comment by olavmrk** [comment]
I think you need a newer version (2.5.0?) of the Lasso library in order to handle SHA-256 signatures. If you have that, it should work automatically in mod_auth_mellon.

**Comment by ABastionOfSanity** [comment]
Is there any verification that mod_auth_mellon with lasso > 2.5.0 supports sha-256?  I am getting the same error with:

mod24_auth_mellon-0.12.0-1.5.amzn1.x86_64
lasso-2.5.1-2.5.amzn1.x86_64

**Comment by olavmrk** [comment]
@ABastionOfSanity: have you verified that it is due to the same cause? I.e. the RSA-SHA256 signature algorithm? The same error message will also occur if there is a different error while validating the signature.

mod_auth_mellon does not do anything to configure which signature algorithms should be used when validating the signature; as far as I can tell, the Lasso library will pick the correct algorithm automatically.
