### ISSUE TITLE
IDP metadata as https URL

### ISSUE THREAD

**Issue by thiyagarajan-k** [UNINETT/mod_auth_mellon#69]
Is it possible to configure the mellon to receive the IDP metadata from https link instead of local file?

**Comment by olavmrk** [comment]
No, it doesn't support automatic metadata fetching. Supporting that normally requires a lot of support infrastructure, since people would expect support for things like signature validation, interpreting of cacheDuration & validUntil attributes, etc.

I don't think that is something that we are going to add to mod_auth_mellon -- it is meant to be a simple SP, after all :smile:
