### ISSUE TITLE
 Unknown POST Content-Type "application/json" when post replay is turned onn

### ISSUE THREAD

**Issue by ismailseyfi** [UNINETT/mod_auth_mellon#72]
We recently turned on mellon's post replay configuration. This started causing some issues within our apache. Our logs indicate  Unknown POST Content-Type "application/json" when the post contains a -H 'Content-Type: application/json'. Any ideas why this is happening? we verified this content type is available within apache.

**Comment by olavmrk** [comment]
Hi,

mod_auth_mellon can only replay simple POST requests caused by normal forms in the web browser. This is due to the way this functionality is implemented. Basically what it does is:

1. Store received POST data.
2. Send user through the SAML 2.0 login process (redirecting to the IdP).
3. After login, send the user to a web page with the POST data embedded in an invisible form, and trigger an autosubmit of this form.

Even if we changed this to handle application/json in some way, I don't think it will solve your problem. I assume that you have a web application that sends data to the server through javascript. That code will not be able to handle a SAML 2.0 login sequence, since that is an off-site redirect, which will hit the browser cross-origin request limits.
